Repository dnd-side-project/dnd-7th-9-frontend, pull requests merged in 2022-07, with the labels that each got.

#1 feature/setting : 초기 환경 셋팅
  .github/PULL_REQUEST_TEMPLATE.md
  .storybook/main.js
  .storybook/preview.js
  .vscode/settings.json
  README.md
  package-lock.json
  package.json
  pages/_app.tsx
  pages/index.tsx
  postcss.config.js
  src/store/store.ts
  src/stories/Button.stories.tsx
  src/stories/Button.tsx
  src/stories/Header.stories.tsx
  src/stories/Header.tsx
  src/stories/Introduction.stories.mdx
  src/stories/Page.stories.tsx
  src/stories/Page.tsx
  src/stories/assets/code-brackets.svg
  src/stories/assets/colors.svg
  src/stories/assets/comments.svg
  src/stories/assets/direction.svg
  src/stories/assets/flow.svg
  src/stories/assets/plugin.svg
  src/stories/assets/repo.svg
  src/stories/assets/stackalt.svg
  src/stories/button.css
  src/stories/header.css
  src/stories/page.css
  styles/globals.css
  tailwind.config.js
Labels: 셋팅

#2 docs: PR 템플릿 수정
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 문서

#5 Feature/store-token
  next.config.js
  pages/index.tsx
  pages/login/index.tsx
  src/app.feature/sign/constant/SocialAuthUrl.ts
  src/store/store.ts
Labels: 셋팅, 기능추가

#7 Feature/token refresh
  src/app.modules/api/client.ts
Labels: 기능추가

#6 Feature/store refresh token
  package-lock.json
  package.json
  pages/_app.tsx
  pages/login/index.tsx
  src/app.modules/cookie/cookie.ts
Labels: 기능추가

#8 fix : refresh token 문제로 인한 access 토큰 갱신 실패 로직 추가
  src/app.modules/api/client.ts
Labels: 기능수정
