Repository dnd-side-project/dnd-7th-9-frontend, pull requests merged in 2022-08, with the labels that each got.

#9 Feature/common button
  public/img/before_active.png
  public/img/before_inactive.png
  public/img/next_active.png
  public/img/next_inactive.png
  public/img/plus.png
  src/app.component/button/DateButton.tsx
  src/app.component/button/DefaultButton.tsx
  src/app.component/button/PageTransitionButton.tsx
  src/app.component/button/PlusButton.tsx
  src/app.component/select/AnswerSelect.tsx
  tailwind.config.js
Labels: 셋팅, 기능추가, 스타일

#12 Feature/footer nav
  .storybook/main.js
  .storybook/preview.js
  package-lock.json
  package.json
  pages/_app.tsx
  pages/index.tsx
  pages/my-goal.tsx
  pages/mypage.tsx
  src/app.component/Layout/index.tsx
  src/app.component/navigation/FooterNav.stories.tsx
  src/app.component/navigation/FooterNav.tsx
  src/assets/nav/ant-design_user-outlined.svg
  src/assets/nav/bx_home-alt-2.svg
  src/assets/nav/material-symbols_quiz-outline.svg
  styles/globals.css
  tailwind.config.js
Labels: 기능추가

#11 Feature/progress bar
  next.config.js
  pages/_app.tsx
  pages/index.tsx
  src/app.component/progressBar/index.tsx
Labels: 기능추가

#13 feature/setting-test
  .storybook/preview.js
  package-lock.json
  package.json
  src/app.component/Layout/index.tsx
  src/app.component/button/DateButton.stories.tsx
  src/app.component/button/DateButton.tsx
  src/app.component/button/DefaultButton.stories.tsx
  src/app.component/button/DefaultButton.tsx
  src/app.component/button/PageTransitionButton.stories.tsx
  src/app.component/button/PageTransitionButton.tsx
  src/app.component/button/PlusButton.stories.tsx
  src/app.component/button/PlusButton.tsx
  src/app.component/select/AnswerSelect.tsx
  src/index.tsx
Labels: 셋팅, 스타일, 버그

#14 Feature/footer nav story
  .storybook/main.js
  .storybook/preview.js
  src/app.component/Layout/index.tsx
  src/app.component/navigation/FooterNav.stories.tsx
  src/app.component/navigation/FooterNav.tsx
  src/app.component/progressBar/ProgressBar.stories.tsx
  src/app.modules/constant/url.ts
Labels: 셋팅, 문서, 기능수정, 버그

#16 Feature/home-UI
  pages/index.tsx
  public/img/before_active.png
  public/img/before_inactive.png
  public/img/next_active.png
  public/img/next_inactive.png
  public/img/plus.png
  src/app.component/Layout/index.tsx
  src/app.component/accordion/Accordion.stories.tsx
  src/app.component/accordion/index.tsx
  src/app.component/button/DefaultButton.tsx
  src/app.component/button/PageTransitionButton.tsx
  src/app.component/button/PlusButton.tsx
  src/app.component/icon/CategoryIcon.stories.tsx
  src/app.component/icon/CategoryIcon.tsx
  src/app.component/title/PageTitle.tsx
  src/app.feature/home/component/accordionContent/StudyGoalAccordionContent.stories.tsx
  src/app.feature/home/component/accordionContent/StudyGoalAccordionContent.tsx
  src/app.feature/home/screen/HomeScreen.tsx
  src/app.modules/util/index.ts
  src/assets/button/left-arrow-able.svg
  src/assets/button/left-arrow-disable.svg
  src/assets/button/plus.svg
  src/assets/button/right-arrow-able.svg
  src/assets/button/right-arrow-disable.svg
  src/assets/category/certification-icon.svg
  src/assets/category/company-icon.svg
  src/assets/category/language-icon.svg
  src/assets/category/test-icon.svg
  src/assets/main/arrow-bottom.svg
  src/assets/main/arrow-top.svg
  src/assets/main/eva_bell-outline.svg
Labels: 기능추가, 스타일

#17 Feature/create study group
  pages/index.tsx
  pages/updated-quizzes.tsx
  src/app.component/Layout/index.tsx
  src/app.component/button/DefaultButton.tsx
  src/app.component/navigation/FooterNav.tsx
  src/app.feature/home/screen/InitHomeScreen.tsx
  src/assets/home/eva_question-mark-outline.svg
Labels: 기능수정

#18 Feature/login
  pages/create-quiz.tsx
  pages/login/index.tsx
  pages/mypage.tsx
  src/app.component/Layout/index.tsx
  src/app.feature/home/screen/InitHomeScreen.tsx
  src/app.feature/sign/component/OauthButton.tsx
  src/app.feature/sign/screen/SignScreen.tsx
  src/app.modules/constant/url.ts
  src/assets/brand/google_icon.svg
  src/assets/brand/kakao_icon.svg
  src/assets/brand/naver_icon.svg
  src/assets/brand/runus_icon.svg
Labels: 기능추가, 스타일

#19 Feature/record-main-UI
  pages/updated-quizzes.tsx
  src/app.component/Layout/index.tsx
  src/app.component/select/AnswerSelect.stories.tsx
  src/app.component/title/PageTitle.stories.tsx
  src/app.component/title/PageTitle.tsx
  src/app.component/title/PageTitleSubContent.stories.tsx
  src/app.component/title/PageTitleSubContent.tsx
  src/app.feature/quiz/component/card/NoneQuizCard.stories.tsx
  src/app.feature/quiz/component/card/NoneQuizCard.tsx
  src/app.feature/quiz/component/card/UpdatedQuizCard.stories.tsx
  src/app.feature/quiz/component/card/UpdatedQuizCard.tsx
  src/app.feature/quiz/screen/UpdatedQuizNoneScreen.tsx
  src/app.feature/quiz/screen/UpdatedQuizScreen.tsx
  src/app.modules/util/index.ts
  src/assets/quiz/arrow-right.svg
  src/assets/quiz/person.svg
  src/assets/quiz/question-mark.svg
Labels: 기능추가, 스타일

#20 Feature/create solve quiz
  .eslintrc
  pages/create-quiz.tsx
  pages/create-quiz/[id].tsx
  pages/solve-quiz/[id].tsx
  src/app.component/button/PageTransitionButton.tsx
  src/app.component/progressBar/index.tsx
  src/app.feature/home/screen/InitHomeScreen.tsx
  src/app.feature/quiz/component/AnswerCheckButton.tsx
  src/app.feature/quiz/component/ChoiceContainer.tsx
  src/app.feature/quiz/component/QuizHeader.tsx
  src/app.feature/quiz/component/QuizPageController.tsx
  src/app.feature/quiz/create-quiz/CreateQuizScreen.tsx
  src/app.feature/quiz/solve-quiz/SolveQuizScreen.tsx
  src/app.modules/store/quiz/createQuiz.tsx
  src/app.modules/store/quiz/solveQuiz.tsx
  src/assets/iconoir_cancel.svg
Labels: 기능추가

#21 Feature/complete-quiz
  package-lock.json
  package.json
  pages/complete/quiz-create.tsx
  pages/complete/quiz-solve.tsx
  src/app.component/button/DefaultButton.tsx
  src/app.component/title/PageTitle.tsx
  src/app.feature/complete/component/animation/QuizCompleteAnimation.stories.tsx
  src/app.feature/complete/component/animation/QuizCompleteAnimation.tsx
  src/app.feature/complete/component/graph/QuizCompleteGraph.stories.tsx
  src/app.feature/complete/component/graph/QuizCompleteGraph.tsx
  src/app.feature/complete/component/graph/QuizCompleteGraphScore.tsx
  src/app.feature/complete/component/title/QuizCreateCompleteTitle.stories.tsx
  src/app.feature/complete/component/title/QuizCreateCompleteTitle.tsx
  src/app.feature/complete/component/title/QuizSolveCompleteTitle.stories.tsx
  src/app.feature/complete/component/title/QuizSolveCompleteTitle.tsx
  src/app.feature/complete/screen/QuizCreateCompleteScreen.tsx
  src/app.feature/complete/screen/QuizSolveCompleteScreen.tsx
  src/app.modules/constant/url.ts
  src/assets/complete/pencil.svg
  src/assets/complete/person.svg
  src/assets/complete/running-person.svg
  tailwind.config.js
Labels: 기능추가

#24 Feature/create study invite member
  pages/complete/invite-member.tsx
  pages/create-study/[id].tsx
  src/app.component/input/Input.stories.tsx
  src/app.component/input/index.tsx
  src/app.feature/complete/component/animation/CompleteAnimation.stories.tsx
  src/app.feature/complete/component/animation/CompleteAnimation.tsx
  src/app.feature/complete/component/animation/QuizCompleteAnimation.stories.tsx
  src/app.feature/complete/component/item/ItemInvitedCompleteMember.stories.tsx
  src/app.feature/complete/component/item/ItemInvitedCompleteMember.tsx
  src/app.feature/complete/screen/InviteStudyMemberCompleteScreen.tsx
  src/app.feature/complete/screen/QuizCreateCompleteScreen.tsx
  src/app.feature/complete/screen/QuizSolveCompleteScreen.tsx
  src/app.feature/create-study/component/drawer/DrawerInviteTeamMember.stories.tsx
  src/app.feature/create-study/component/drawer/DrawerInviteTeamMember.tsx
  src/app.feature/create-study/component/item/ItemInvitedMember.stories.tsx
  src/app.feature/create-study/component/item/ItemInvitedMember.tsx
  src/app.feature/create-study/screen/CreateStudyLastScreen.tsx
  src/assets/complete/firecracker.svg
  src/assets/create-study/cancel.svg
  tailwind.config.js
Labels: 기능추가

#25 Feature/create study group
  pages/create-quiz/[id].tsx
  pages/create-study/[id].tsx
  src/app.component/box/index.tsx
  src/app.component/header/Progress.stories.tsx
  src/app.component/header/Progress.tsx
  src/app.component/modal/BackAlertModal.tsx
  src/app.component/modal/layout.tsx
  src/app.component/pageController/PageController.stories.tsx
  src/app.component/pageController/PageController.tsx
  src/app.feature/create-study/component/layout/index.tsx
  src/app.feature/create-study/component/requireMark/RequireMark.stories.tsx
  src/app.feature/create-study/component/requireMark/RequireMark.tsx
  src/app.feature/create-study/screen/IntroduceStudyScreen.tsx
  src/app.feature/create-study/screen/StudyDateScreen.tsx
  src/app.feature/create-study/screen/StudyGoalScreen.tsx
  src/app.feature/quiz/component/container/ChoiceContainer.stories.tsx
  src/app.feature/quiz/component/container/ChoiceContainer.tsx
  src/app.feature/quiz/component/header/QuizHeader.tsx
  src/app.feature/quiz/screen/CreateQuizScreen.tsx
  src/app.feature/quiz/screen/DetailQuizScreen.tsx
  src/app.feature/quiz/screen/SolveQuizScreen.tsx
  src/app.modules/store/study/createStudy.tsx
  src/assets/iconoir_cancel.svg
  src/assets/modal/akar-icons_circle-alert-fill.svg
  src/assets/study/certification_icon.svg
  src/assets/study/company_icon.svg
  src/assets/study/exam_icon.svg
  src/assets/study/language_icon.svg
Labels: 기능추가

#26 Feature/mypage-UI
  pages/mypage.tsx
  pages/mypage/index.tsx
  src/app.component/accordion/index.tsx
  src/app.component/icon/CategoryIcon.tsx
  src/app.feature/login/constant/SocialAuthUrl.ts
  src/app.feature/mypage/component/accordian-content/MyPageStudyAccordionContent.stories.tsx
  src/app.feature/mypage/component/accordian-content/MyPageStudyAccordionContent.tsx
  src/app.feature/mypage/component/category/MyPageStudyCategory.stories.tsx
  src/app.feature/mypage/component/category/MyPageStudyCategory.tsx
  src/app.feature/mypage/component/profile/MyPageUserProfile.stories.tsx
  src/app.feature/mypage/component/profile/MyPageUserProfile.tsx
  src/app.feature/mypage/component/toggle/MyPageStudyStatusToggle.stories.tsx
  src/app.feature/mypage/component/toggle/MyPageStudyStatusToggle.tsx
  src/app.feature/mypage/screen/MyPageNoneStudyScreen.tsx
  src/app.feature/mypage/screen/MyPageScreen.tsx
  src/assets/mypage/bell.svg
  src/assets/mypage/no-study.svg
  src/assets/mypage/user.svg
  tailwind.config.js
Labels: 기능추가

#27 Feature/study detail
  pages/create-quiz/[id].tsx
  pages/detail-quiz/[id].tsx
  pages/index.tsx
  pages/login/index.tsx
  pages/solve-quiz/[id].tsx
  pages/studies/[id]/index.tsx
  pages/studies/[id]/members.tsx
  src/app.component/button/DefaultButton.tsx
  src/app.component/header/GoBack.tsx
  src/app.component/modal/BackAlertModal.tsx
  src/app.feature/detail-study/component/Collection.tsx
  src/app.feature/detail-study/component/DetailGoalProgress.tsx
  src/app.feature/detail-study/component/DetailGoals.tsx
  src/app.feature/detail-study/component/MyCollection.tsx
  src/app.feature/detail-study/component/header.tsx
  src/app.feature/detail-study/screen/DetailStudyScreen.tsx
  src/app.feature/detail-study/screen/StudyMembersScreen.tsx
  src/app.feature/quiz/screen/SolveQuizScreen.tsx
  src/assets/study/akar-icons_person.svg
  src/assets/study/fluent_document-edit-20-regular.svg
  src/assets/study/plus_icon.svg
Labels: 기능추가

#30 feat : 문제가 이상해요 모달
  src/app.component/modal/BackAlertModal.tsx
  src/app.component/modal/ReportIssueModal.tsx
  src/app.component/modal/layout.tsx
  src/app.feature/create-study/component/layout/index.tsx
  src/app.feature/detail-study/screen/StudyMembersScreen.tsx
  src/app.feature/quiz/screen/DetailQuizScreen.tsx
Labels: 기능추가

#29 Feature/main-api
  package-lock.json
  package.json
  pages/_app.tsx
  pages/updated-quizzes.tsx
  src/app.feature/quiz/component/card/UpdatedQuizCard.tsx
  src/app.feature/quiz/screen/UpdatedQuizScreen.tsx
Labels: 셋팅

#28 Feature/create-detail-object-UI
  pages/create-detail-goal/[id].tsx
  src/app.component/input/index.tsx
  src/app.component/requireMark/RequireMark.stories.tsx
  src/app.component/requireMark/RequireMark.tsx
  src/app.feature/create-detail-goal/component/control/ControlCountDetailGoal.tsx
  src/app.feature/create-detail-goal/component/layout/LayoutCreateDetailGoalByInput.tsx
  src/app.feature/create-detail-goal/component/layout/LayoutCreateDetailGoalBySelect.tsx
  src/app.feature/create-detail-goal/screen/CreateDetailGoalScreenByContent.tsx
  src/app.feature/create-detail-goal/screen/CreateDetailGoalScreenByCorrectCount.tsx
  src/app.feature/create-detail-goal/screen/CreateDetailGoalScreenByDate.tsx
  src/app.feature/create-detail-goal/screen/CreateDetailGoalScreenByPassMember.tsx
  src/app.feature/create-detail-goal/screen/CreateDetailGoalScreenByQuizCount.tsx
  src/app.feature/create-detail-goal/screen/CreateDetailGoalScreenBySolveQuiz.tsx
  src/app.feature/create-study/screen/IntroduceStudyScreen.tsx
  src/app.feature/create-study/screen/StudyDateScreen.tsx
  src/app.feature/create-study/screen/StudyGoalScreen.tsx
  src/app.modules/store/create-detail-goal/createDetailGoal.ts
  src/assets/create-detail-object/disabled-minus.svg
  src/assets/create-detail-object/disabled-plus.svg
  src/assets/create-detail-object/member-solve.svg
  src/assets/create-detail-object/member.svg
  src/assets/create-detail-object/minus.svg
  src/assets/create-detail-object/plus.svg
  src/assets/create-detail-object/quiz.svg
  src/assets/create-detail-object/solve.svg
Labels: 기능추가

#31 fix: 소셜 로그인 api uri 수정
  src/app.feature/login/constant/SocialAuthUrl.ts
Labels: 기능수정
